package data.writer

import data.parser.a2l.EcuEntry
import java.io.File
import java.nio.charset.Charset

/**
 * Generates ME7Logger-compatible .ecu and .cfg files from parsed A2L data.
 */
object EcuWriter {

    private val LATIN1 = Charset.forName("ISO-8859-1")

    /**
     * Write ME7Logger-compatible .ecu characteristics file.
     */
    fun writeEcuFile(
        entries: List<EcuEntry>,
        outputFile: File,
        partNumber: String = "1K0907115S",
        swNumber: String = "0261S02469",
        engineId: String = "2.0L R4 TFSI"
    ) {
        outputFile.bufferedWriter(LATIN1).use { w ->
            w.write(";\n")
            w.write("; ECU characteristics for logging with ME7Logger\n")
            w.write(";\n")
            w.write("; Generated by MxT A2L→ECU Generator\n")
            w.write(";\n")
            w.write("; Part number: $partNumber\n")
            w.write("; SW number:   $swNumber\n")
            w.write("; Engine:      $engineId\n")
            w.write(";\n")
            w.write("; NOTE: RAM addresses are SW-version specific.\n")
            w.write("; Other SW versions will have DIFFERENT addresses.\n")
            w.write(";\n\n")

            w.write("[Version]\n")
            w.write("Version           = 1.10\n\n")

            w.write("[Communication]\n")
            w.write("Connect      = SLOW-0x01    ; 5-baud init at address 0x01\n")
            w.write("Communicate  = HM0          ; Headerless mode\n")
            w.write("LogSpeed     = 56000        ; baud rate\n\n")

            w.write("[Identification]\n")
            w.write("HWNumber          = {$partNumber}\n")
            w.write("SWNumber          = {$swNumber}\n")
            w.write("PartNumber        = {$partNumber}\n")
            w.write("SWVersion         = {0001}\n")
            w.write("EngineId          = {$engineId}\n\n")

            w.write("[Measurements]\n")
            w.write("; Conversion: Normal: phys = Factor * raw - Offset\n")
            w.write(";             Inverse: phys = Factor / (raw - Offset)\n")
            w.write(";\n")

            for (e in entries) {
                val aliasStr = if (e.alias.isNotEmpty()) "{${e.alias}}" else "{}"
                val unitStr = if (e.unit.isNotEmpty()) "{${e.unit}}" else "{}"
                val commentStr = if (e.comment.isNotEmpty()) "{${e.comment}}" else "{}"
                val factorStr = formatFactor(e.factor)
                val offsetStr = formatFactor(e.offset)

                w.write(
                    "${e.name.padEnd(16)}, ${aliasStr.padEnd(36)}, " +
                        "0x${String.format("%06X", e.address)}, ${e.size.toString().padStart(2)}, " +
                        "0x${String.format("%04X", e.bitmask)},  ${unitStr.padEnd(10)}, " +
                        "${e.signed}, ${e.inverse}, " +
                        "${factorStr.padStart(14)}, ${offsetStr.padStart(7)}, " +
                        "$commentStr\n"
                )
            }
        }
    }

    /**
     * Write ME7Logger .cfg log configuration file.
     *
     * @param variables list of (name, aliasComment, descComment) triples
     */
    fun writeCfgFile(
        outputFile: File,
        ecuFilename: String,
        variables: List<Triple<String, String, String>>,
        samplesPerSecond: Int = 20,
        description: String = ""
    ) {
        outputFile.bufferedWriter(LATIN1).use { w ->
            w.write(";\n")
            w.write("; $description\n")
            w.write("; Generated by MxT A2L→ECU Generator\n")
            w.write(";\n\n")

            w.write("[Configuration]\n")
            w.write("ECUCharacteristics = $ecuFilename\n")
            w.write("SamplesPerSecond   = $samplesPerSecond\n\n")

            w.write("[LogVariables]\n")
            w.write(";Name            [Alias]                             [; Comment]\n")

            for ((name, aliasComment, descComment) in variables) {
                if (name.isEmpty()) {
                    w.write("\n")
                    continue
                }
                val sb = StringBuilder(name.padEnd(17))
                if (aliasComment.isNotEmpty()) {
                    sb.append(";{$aliasComment}")
                    if (descComment.isNotEmpty()) {
                        val padding = maxOf(1, 36 - aliasComment.length - 2)
                        sb.append(" ".repeat(padding))
                    }
                }
                if (descComment.isNotEmpty()) {
                    sb.append(" ; {$descComment}")
                }
                w.write(sb.toString().trimEnd() + "\n")
            }
        }
    }

    /** Basic tuning .cfg preset variables. */
    val BASIC_VARIABLES = listOf(
        Triple("nmot_w", "EngineSpeed", "Engine speed"),
        Triple("rl_w", "EngineLoad", "Relative load"),
        Triple("rlsol_w", "EngineLoadRequested", "Requested load"),
        Triple("mshfm_w", "MassAirFlow", "MAF mass flow"),
        Triple("pvdks_w", "BoostPressureActual", "Actual manifold pressure"),
        Triple("plsol_w", "BoostPressureSpecified", "Requested boost"),
        Triple("ldtvm", "WastegateDutyCycle", "Wastegate duty cycle"),
        Triple("fr_w", "LambdaControl", "Short-term fuel trim"),
        Triple("fra_w", "AdaptationPartial", "Long-term fuel trim"),
        Triple("ti_w", "InjectionTime", "Injection time"),
        Triple("zwist", "IgnitionTimingAngle", "Ignition timing"),
        Triple("lamsbg_w", "AirFuelRatioRequired", "Requested lambda"),
        Triple("lamsoni_w", "AirFuelRatioCurrent", "Actual lambda"),
        Triple("wdkba", "ThrottlePlateAngle", "Throttle angle"),
        Triple("tmot", "CoolantTemperature", "Coolant temp"),
        Triple("tans", "IntakeAirTemperature", "Intake air temp"),
        Triple("wub", "BatteryVoltage", "Battery voltage"),
        Triple("vfil_w", "VehicleSpeed", "Vehicle speed"),
    )

    /** LDRPID-focused .cfg preset variables. */
    val LDRPID_VARIABLES = listOf(
        Triple("nmot_w", "EngineSpeed", "Engine speed"),
        Triple("rl_w", "EngineLoad", "Relative load"),
        Triple("rlsol_w", "EngineLoadRequested", "Requested load"),
        Triple("pvdks_w", "BoostPressureActual", "Actual manifold pressure"),
        Triple("pssol_w", "ManifoldPressureRequested", "Requested manifold pressure"),
        Triple("plsol_w", "BoostPressureSpecified", "Requested boost"),
        Triple("ldtvm", "WastegateDutyCycle", "Wastegate duty cycle"),
        Triple("wped_w", "AccelPedalPosition", "Accel pedal position"),
        Triple("wdkba", "ThrottlePlateAngle", "Throttle angle"),
        Triple("zwist", "IgnitionTimingAngle", "Ignition timing"),
        Triple("lamsoni_w", "AirFuelRatioCurrent", "Actual lambda"),
        Triple("gangi", "SelectedGear", "Selected gear"),
        Triple("vfil_w", "VehicleSpeed", "Vehicle speed"),
    )

    private fun formatFactor(f: Double): String {
        if (f == f.toLong().toDouble() && kotlin.math.abs(f) < 1e6) {
            return f.toLong().toString()
        }
        if (kotlin.math.abs(f) >= 0.001) {
            return f.toBigDecimal().stripTrailingZeros().toPlainString()
        }
        return String.format("%.6e", f)
    }
}
