package data.writer

import domain.model.optimizer.*
import domain.model.simulator.MechanicalLimitDetector
import domain.model.simulator.SafetyModeDetector
import domain.model.simulator.TransientDetector
import java.io.File

/**
 * Phase 23: Export a full HTML analysis report.
 *
 * Generates a self-contained HTML file with all optimizer results including
 * chain health, map deltas, convergence data, and recommendations.
 */
object ReportExporter {

    fun export(
        outputFile: File,
        result: OptimizerCalculator.OptimizerResult,
        pulls: List<PullSegmenter.WotPull> = emptyList(),
        transients: TransientDetector.TransientResult? = null,
        safetyModes: SafetyModeDetector.SafetyModeResult? = null,
        convergence: IterativeConvergence.ConvergenceHistory? = null,
        kfurlResult: KfurlSolver.SolverResult? = null,
        ldrxnTarget: Double = 191.0
    ) {
        val html = buildString {
            appendLine("<!DOCTYPE html>")
            appendLine("<html lang='en'><head>")
            appendLine("<meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'>")
            appendLine("<title>MxT Optimizer Report</title>")
            appendLine("<style>")
            appendLine(CSS)
            appendLine("</style></head><body>")

            appendLine("<h1>🏎️ MxT Optimizer Report</h1>")
            appendLine("<p class='subtitle'>Generated by MxT v4 • ${java.time.LocalDateTime.now()}</p>")
            appendLine("<hr>")

            // ── Chain Health ────────────────────────────────
            val diag = result.chainDiagnosis
            appendLine("<h2>Chain Health</h2>")
            appendLine("<table class='health'>")
            healthRow("Link 1: LDRXN → rlsol (Torque)", 100.0 - diag.torqueCappedPercent)
            healthRow("Link 2: rlsol → pssol (VE Forward)", 100.0 - diag.pssolErrorPercent)
            healthRow("Link 3: pssol → pvdks (Boost Control)", 100.0 - diag.boostShortfallPercent)
            healthRow("Link 4: pvdks → rl_w (VE Reverse)", 100.0 - diag.veMismatchPercent)
            appendLine("</table>")

            // ── Mechanical Limits ───────────────────────────
            val lim = result.mechanicalLimits
            appendLine("<h2>Mechanical Limits</h2>")
            appendLine("<table class='limits'>")
            appendLine("<tr><th>Component</th><th>Status</th><th>Detail</th></tr>")
            limitRow("MAF Sensor", !lim.mafMaxed, if (lim.mafMaxValue > 0) "${f0(lim.mafMaxValue)} g/s" else "N/A")
            limitRow("Injectors", !lim.injectorMaxed, if (lim.injectorMaxDutyCycle > 0) "${f0(lim.injectorMaxDutyCycle * 100)}% DC" else "N/A")
            limitRow("Turbo", !lim.turboMaxed, if (lim.turboMaxWgdc > 0) "${f0(lim.turboMaxWgdc)}% WGDC" else "N/A")
            limitRow("MAP Sensor", !lim.mapSensorMaxed, if (lim.mapSensorMaxValue > 0) "${f0(lim.mapSensorMaxValue)} mbar" else "N/A")
            appendLine("</table>")

            // ── Suggested Maps ──────────────────────────────
            val sm = result.suggestedMaps
            appendLine("<h2>Suggested Map Corrections</h2>")
            appendLine("<table class='maps'>")
            appendLine("<tr><th>Map</th><th>Cells Modified</th><th>Coverage</th><th>Avg Δ</th></tr>")
            sm.kfmiop?.let { mapRow("KFMIOP", it) }
            sm.kfmirl?.let { mapRow("KFMIRL", it) }
            sm.kfpbrk?.let { mapRow("KFPBRK", it) }
            sm.kfldrl?.let { mapRow("KFLDRL", it) }
            sm.kfldimx?.let { mapRow("KFLDIMX", it) }
            appendLine("</table>")

            // ── Per-Pull Summary ─────────────────────────────
            if (pulls.isNotEmpty()) {
                appendLine("<h2>Per-Pull Analysis (${pulls.size} pulls)</h2>")
                appendLine("<table class='pulls'>")
                appendLine("<tr><th>#</th><th>RPM Range</th><th>Samples</th><th>Quality</th><th>Avg ΔP (mbar)</th><th>Avg Load Deficit</th></tr>")
                for (pull in pulls) {
                    val qualityEmoji = when (pull.quality) {
                        PullSegmenter.PullQuality.GOOD -> "🟢"
                        PullSegmenter.PullQuality.NOISY -> "🟡"
                        PullSegmenter.PullQuality.SHORT -> "🟠"
                        PullSegmenter.PullQuality.INCOMPLETE -> "🔴"
                    }
                    appendLine("<tr><td>${pull.pullIndex + 1}</td>" +
                        "<td>${f0(pull.rpmStart)} – ${f0(pull.rpmEnd)}</td>" +
                        "<td>${pull.sampleCount}</td>" +
                        "<td>$qualityEmoji ${pull.quality}</td>" +
                        "<td>${fp(pull.avgPressureError)}</td>" +
                        "<td>${fp(pull.avgLoadDeficit)}</td></tr>")
                }
                appendLine("</table>")
            }

            // ── Transient Events ─────────────────────────────
            if (transients != null && transients.events.isNotEmpty()) {
                appendLine("<h2>Transient Events</h2>")
                appendLine("<table class='events'>")
                appendLine("<tr><th>Type</th><th>Samples</th><th>Avg RPM</th><th>Peak Magnitude</th><th>Description</th></tr>")
                for (event in transients.events) {
                    appendLine("<tr><td>${event.type}</td><td>${event.sampleCount}</td>" +
                        "<td>${f0(event.avgRpm)}</td><td>${f1(event.peakMagnitude)}</td>" +
                        "<td>${event.description}</td></tr>")
                }
                appendLine("</table>")
            }

            // ── Convergence ──────────────────────────────────
            if (convergence != null) {
                appendLine("<h2>Iterative Convergence</h2>")
                val status = when {
                    convergence.converged -> "✅ Converged in ${convergence.iterationsToConverge} iterations"
                    convergence.diverged -> "❌ Diverged after ${convergence.iterationsToConverge} iterations"
                    else -> "⚠️ Did not converge in ${convergence.steps.size} iterations"
                }
                appendLine("<p>$status (final error: ${f2(convergence.finalError)})</p>")
                appendLine("<table class='convergence'>")
                appendLine("<tr><th>Iteration</th><th>Total Error</th><th>Pressure Error</th><th>Load Deficit</th><th>Cells Modified</th></tr>")
                for (step in convergence.steps) {
                    appendLine("<tr><td>${step.iteration}</td><td>${f2(step.totalError)}</td>" +
                        "<td>${f1(step.avgPressureError)}</td><td>${f1(step.avgLoadDeficit)}</td>" +
                        "<td>${step.cellsModified}</td></tr>")
                }
                appendLine("</table>")
            }

            // ── Recommendations ──────────────────────────────
            if (diag.recommendations.isNotEmpty()) {
                appendLine("<h2>Recommendations</h2>")
                appendLine("<ol>")
                for (rec in diag.recommendations) {
                    appendLine("<li>$rec</li>")
                }
                appendLine("</ol>")
            }

            // ── Warnings ─────────────────────────────────────
            if (result.warnings.isNotEmpty()) {
                appendLine("<h2>Warnings</h2>")
                appendLine("<ul class='warnings'>")
                for (w in result.warnings) {
                    appendLine("<li>$w</li>")
                }
                appendLine("</ul>")
            }

            // ── Log Summary ──────────────────────────────────
            appendLine("<h2>Log Summary</h2>")
            appendLine("<p>WOT Samples: ${result.wotEntries.size}</p>")
            if (result.wotEntries.isNotEmpty()) {
                appendLine("<p>RPM Range: ${result.wotEntries.minOf { it.rpm }.toInt()} – ${result.wotEntries.maxOf { it.rpm }.toInt()}</p>")
            }
            if (result.logSummaries.isNotEmpty()) {
                appendLine("<p>Log Files: ${result.logSummaries.size}</p>")
                appendLine("<table class='logs'>")
                appendLine("<tr><th>File</th><th>WOT Samples</th><th>RPM Range</th><th>Avg ΔP</th></tr>")
                for (ls in result.logSummaries) {
                    appendLine("<tr><td>${ls.fileName}</td><td>${ls.wotSampleCount}</td>" +
                        "<td>${ls.rpmRange}</td><td>${fp(ls.avgPressureError)} mbar</td></tr>")
                }
                appendLine("</table>")
            }

            appendLine("<hr><p class='footer'>MxT Optimizer v4 • github.com/TracqiTechnology/MxT</p>")
            appendLine("</body></html>")
        }

        outputFile.writeText(html)
    }

    // ── HTML helpers ───────────────────────────────────────────────

    private fun StringBuilder.healthRow(label: String, okPercent: Double) {
        val clamped = okPercent.coerceIn(0.0, 100.0)
        val color = when {
            clamped >= 90 -> "#4CAF50"
            clamped >= 70 -> "#FF9800"
            else -> "#F44336"
        }
        appendLine("<tr><td>$label</td><td><div class='bar'><div class='fill' style='width:${clamped.toInt()}%;background:$color'></div></div></td><td>${f0(clamped)}% OK</td></tr>")
    }

    private fun StringBuilder.limitRow(name: String, ok: Boolean, detail: String) {
        val icon = if (ok) "🟢" else "🔴"
        appendLine("<tr><td>$name</td><td>$icon ${if (ok) "OK" else "MAXED"}</td><td>$detail</td></tr>")
    }

    private fun StringBuilder.mapRow(name: String, delta: MapDelta) {
        appendLine("<tr><td>$name</td><td>${delta.cellsModified}/${delta.totalCells}</td>" +
            "<td>${f0(delta.coverage * 100)}%</td><td>${f2(delta.avgAbsoluteDelta)}</td></tr>")
    }

    private fun f0(v: Double) = String.format("%.0f", v)
    private fun f1(v: Double) = String.format("%.1f", v)
    private fun f2(v: Double) = String.format("%.2f", v)
    private fun fp(v: Double) = String.format("%+.0f", v)

    private val CSS = """
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; background: #1a1a2e; color: #e0e0e0; }
        h1 { color: #00BCD4; } h2 { color: #1976D2; border-bottom: 1px solid #333; padding-bottom: 8px; }
        .subtitle { color: #888; } .footer { color: #666; text-align: center; }
        table { border-collapse: collapse; width: 100%; margin: 12px 0; }
        th, td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #333; }
        th { background: #252540; color: #00BCD4; }
        tr:hover { background: #252540; }
        .bar { width: 200px; height: 16px; background: #333; border-radius: 4px; display: inline-block; }
        .fill { height: 100%; border-radius: 4px; }
        .warnings li { color: #FF9800; margin: 4px 0; }
        hr { border: none; border-top: 1px solid #333; margin: 24px 0; }
    """.trimIndent()
}

