package data.writer

import data.parser.xdf.AxisDefinition
import data.parser.xdf.TableDefinition
import data.parser.xdf.XdfHeader
import java.io.File

/**
 * Generates TunerPro-compatible XDF definition files.
 *
 * XDF files are XML documents that define how to read ECU map data from a
 * binary file. This generator produces XDF files that are compatible with
 * both TunerPro and our own [data.parser.xdf.XdfParser].
 *
 * ## Usage
 * ```kotlin
 * val generator = XdfGenerator(
 *     title = "06A906018CJ",
 *     description = "M3.8.3 1.8T AGU 150PS",
 *     author = "MxT OLS converter"
 * )
 * generator.addTable(table)
 * generator.addConstant(constant)
 * generator.writeTo(File("output.xdf"))
 * ```
 *
 * ## XDF format reference
 * The generated XML follows TunerPro XDF 1.50 format:
 * - XDFHEADER: file metadata, BASEOFFSET, DEFAULTS, CATEGORYs
 * - XDFTABLE: 2D/1D maps with x/y/z axes
 * - XDFCONSTANT: scalar values
 */
class XdfGenerator(
    private val title: String,
    private val description: String = "",
    private val author: String = "MxT XdfGenerator",
    private val baseOffset: Int = 0,
    private val baseOffsetSubtract: Boolean = false,
    private val defaultSizeBits: Int = 8,
    private val defaultLsbFirst: Boolean = true,
    private val defaultSigned: Boolean = false
) {
    private val tables = mutableListOf<TableEntry>()
    private val constants = mutableListOf<ConstantEntry>()
    private val categories = mutableMapOf<Int, String>()

    // ── Public API ──────────────────────────────────────────────────────

    fun addCategory(index: Int, name: String) {
        categories[index] = name
    }

    fun addTable(
        name: String,
        description: String = "",
        categoryIndex: Int = 0,
        xAxis: AxisSpec? = null,
        yAxis: AxisSpec? = null,
        zAxis: AxisSpec
    ) {
        tables.add(TableEntry(name, description, categoryIndex, xAxis, yAxis, zAxis))
    }

    fun addConstant(
        name: String,
        description: String = "",
        categoryIndex: Int = 0,
        address: Int,
        sizeBits: Int = 8,
        signed: Boolean = false,
        lsbFirst: Boolean = defaultLsbFirst,
        unit: String = "",
        equation: String = "X",
        decimalPl: Int = 2
    ) {
        constants.add(ConstantEntry(
            name, description, categoryIndex, address, sizeBits,
            signed, lsbFirst, unit, equation, decimalPl
        ))
    }

    /**
     * Generate the XDF XML content as a string.
     */
    fun generate(): String {
        val sb = StringBuilder()
        sb.appendLine("""<!-- Generated by MxT XdfGenerator -->""")
        sb.appendLine("""<XDFFORMAT version="1.50">""")

        generateHeader(sb)
        tables.forEach { generateTable(sb, it) }
        constants.forEach { generateConstant(sb, it) }

        sb.appendLine("</XDFFORMAT>")
        return sb.toString()
    }

    /**
     * Write the XDF to a file.
     */
    fun writeTo(file: File) {
        file.writeText(generate(), Charsets.UTF_8)
    }

    // ── Header generation ───────────────────────────────────────────────

    private fun generateHeader(sb: StringBuilder) {
        sb.appendLine("  <XDFHEADER>")
        sb.appendLine("    <fileversion>Version 1</fileversion>")
        sb.appendLine("    <deftitle>${escapeXml(title)}</deftitle>")
        if (description.isNotBlank()) {
            sb.appendLine("    <description>${escapeXml(description)}</description>")
        }
        sb.appendLine("    <author>${escapeXml(author)}</author>")
        sb.appendLine("    <baseoffset>$baseOffset</baseoffset>")

        val signedVal = if (defaultSigned) "1" else "0"
        val lsbVal = if (defaultLsbFirst) "1" else "0"
        sb.appendLine("""    <DEFAULTS datasizeinbits="$defaultSizeBits" sigdigits="2" outputtype="1" signed="$signedVal" lsbfirst="$lsbVal" float="0" />""")

        sb.appendLine("""    <REGION type="0xFFFFFFFF" startaddress="0x0" size="0x${(256 * 1024).toString(16).uppercase()}" regionflags="0x0" name="Binary File" desc="This region describes the bin file edited by this XDF" />""")

        for ((index, name) in categories.toSortedMap()) {
            sb.appendLine("""    <CATEGORY index="0x${index.toString(16).uppercase()}" name="${escapeXml(name)}" />""")
        }

        sb.appendLine("  </XDFHEADER>")
    }

    // ── Table generation ────────────────────────────────────────────────

    private fun generateTable(sb: StringBuilder, entry: TableEntry) {
        sb.appendLine("""  <XDFTABLE uniqueid="0x0" flags="0x0">""")
        sb.appendLine("    <title>${escapeXml(entry.name)}</title>")
        if (entry.description.isNotBlank()) {
            sb.appendLine("    <description>${escapeXml(entry.description)}</description>")
        }
        sb.appendLine("""    <CATEGORYMEM index="0" category="${entry.categoryIndex}" />""")

        // X axis
        if (entry.xAxis != null) {
            generateAxis(sb, "x", entry.xAxis)
        } else {
            generateVirtualAxis(sb, "x", 1)
        }

        // Y axis
        if (entry.yAxis != null) {
            generateAxis(sb, "y", entry.yAxis)
        } else {
            generateVirtualAxis(sb, "y", entry.zAxis.rowCount)
        }

        // Z axis
        generateZAxis(sb, entry.zAxis)

        sb.appendLine("  </XDFTABLE>")
    }

    private fun generateAxis(sb: StringBuilder, id: String, axis: AxisSpec) {
        sb.appendLine("""    <XDFAXIS id="$id" uniqueid="0x0">""")

        if (axis.address >= 0) {
            val typeFlags = buildTypeFlags(axis.signed, axis.lsbFirst)
            val typeFlagStr = if (typeFlags != 0) """ mmedtypeflags="0x${typeFlags.toString(16).uppercase().padStart(2, '0')}"""" else ""
            sb.appendLine("""      <EMBEDDEDDATA${typeFlagStr} mmedaddress="0x${axis.address.toString(16).uppercase()}" mmedelementsizebits="${axis.sizeBits}" mmedmajorstridebits="${axis.sizeBits}" />""")
            sb.appendLine("""      <embedinfo type="1" />""")
        } else {
            sb.appendLine("""      <EMBEDDEDDATA mmedelementsizebits="${axis.sizeBits}" mmedmajorstridebits="-32" />""")
        }

        sb.appendLine("      <units>${escapeXml(axis.unit)}</units>")
        sb.appendLine("      <indexcount>${axis.count}</indexcount>")
        sb.appendLine("      <decimalpl>${axis.decimalPl}</decimalpl>")

        if (axis.address < 0 && axis.labels.isNotEmpty()) {
            sb.appendLine("      <datatype>0</datatype>")
            sb.appendLine("      <unittype>0</unittype>")
            sb.appendLine("""      <DALINK index="0" />""")
            axis.labels.forEachIndexed { index, label ->
                sb.appendLine("""      <LABEL index="$index" value="$label" />""")
            }
        }

        sb.appendLine("""      <MATH equation="${escapeXml(axis.equation)}">""")
        sb.appendLine("""        <VAR id="X" />""")
        sb.appendLine("      </MATH>")
        sb.appendLine("    </XDFAXIS>")
    }

    private fun generateVirtualAxis(sb: StringBuilder, id: String, count: Int) {
        sb.appendLine("""    <XDFAXIS id="$id" uniqueid="0x0">""")
        sb.appendLine("""      <EMBEDDEDDATA mmedelementsizebits="16" mmedmajorstridebits="-32" />""")
        sb.appendLine("      <units>-</units>")
        sb.appendLine("      <indexcount>$count</indexcount>")
        sb.appendLine("      <decimalpl>0</decimalpl>")
        sb.appendLine("      <outputtype>2</outputtype>")
        sb.appendLine("      <datatype>0</datatype>")
        sb.appendLine("      <unittype>0</unittype>")
        sb.appendLine("""      <DALINK index="0" />""")
        for (i in 0 until count) {
            sb.appendLine("""      <LABEL index="$i" value="${if (i == 0) "" else "$i"}" />""")
        }
        sb.appendLine("""      <MATH equation="X">""")
        sb.appendLine("""        <VAR id="X" />""")
        sb.appendLine("      </MATH>")
        sb.appendLine("    </XDFAXIS>")
    }

    private fun generateZAxis(sb: StringBuilder, z: AxisSpec) {
        sb.appendLine("""    <XDFAXIS id="z">""")

        val typeFlags = buildTypeFlags(z.signed, z.lsbFirst)
        val typeFlagStr = if (typeFlags != 0) """ mmedtypeflags="0x${typeFlags.toString(16).uppercase().padStart(2, '0')}"""" else ""
        sb.appendLine("""      <EMBEDDEDDATA${typeFlagStr} mmedaddress="0x${z.address.toString(16).uppercase()}" mmedelementsizebits="${z.sizeBits}" mmedrowcount="${z.rowCount}" mmedcolcount="${z.colCount}" />""")

        sb.appendLine("      <units>${escapeXml(z.unit)}</units>")
        sb.appendLine("      <decimalpl>${z.decimalPl}</decimalpl>")
        if (!z.min.isNaN()) sb.appendLine("      <min>${z.min}</min>")
        if (!z.max.isNaN()) sb.appendLine("      <max>${z.max}</max>")
        sb.appendLine("      <outputtype>1</outputtype>")
        sb.appendLine("""      <MATH equation="${escapeXml(z.equation)}">""")
        sb.appendLine("""        <VAR id="X" />""")
        sb.appendLine("      </MATH>")
        sb.appendLine("    </XDFAXIS>")
    }

    // ── Constant generation ─────────────────────────────────────────────

    private fun generateConstant(sb: StringBuilder, entry: ConstantEntry) {
        sb.appendLine("""  <XDFCONSTANT uniqueid="0x0">""")
        sb.appendLine("    <title>${escapeXml(entry.name)}</title>")
        if (entry.description.isNotBlank()) {
            sb.appendLine("    <description>${escapeXml(entry.description)}</description>")
        }
        sb.appendLine("""    <CATEGORYMEM index="0" category="${entry.categoryIndex}" />""")

        val typeFlags = buildTypeFlags(entry.signed, entry.lsbFirst)
        val typeFlagStr = if (typeFlags != 0) """ mmedtypeflags="0x${typeFlags.toString(16).uppercase().padStart(2, '0')}"""" else ""
        sb.appendLine("""    <EMBEDDEDDATA${typeFlagStr} mmedaddress="0x${entry.address.toString(16).uppercase()}" mmedelementsizebits="${entry.sizeBits}" />""")

        sb.appendLine("    <units>${escapeXml(entry.unit)}</units>")
        sb.appendLine("    <decimalpl>${entry.decimalPl}</decimalpl>")
        sb.appendLine("    <outputtype>1</outputtype>")
        sb.appendLine("""    <MATH equation="${escapeXml(entry.equation)}">""")
        sb.appendLine("""      <VAR id="X" />""")
        sb.appendLine("    </MATH>")
        sb.appendLine("  </XDFCONSTANT>")
    }

    // ── Helpers ─────────────────────────────────────────────────────────

    private fun buildTypeFlags(signed: Boolean, lsbFirst: Boolean): Int {
        var flags = 0
        if (signed) flags = flags or 0x01
        if (lsbFirst) flags = flags or 0x02
        return flags
    }

    private fun escapeXml(text: String): String = text
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\"", "&quot;")

    // ── Data classes ────────────────────────────────────────────────────

    private data class TableEntry(
        val name: String,
        val description: String,
        val categoryIndex: Int,
        val xAxis: AxisSpec?,
        val yAxis: AxisSpec?,
        val zAxis: AxisSpec
    )

    private data class ConstantEntry(
        val name: String,
        val description: String,
        val categoryIndex: Int,
        val address: Int,
        val sizeBits: Int,
        val signed: Boolean,
        val lsbFirst: Boolean,
        val unit: String,
        val equation: String,
        val decimalPl: Int
    )
}

/**
 * Specification for an axis in a generated XDF table.
 *
 * @property address   Binary address (mmedaddress). Use -1 for virtual/label-only axes.
 * @property count     Number of elements (indexcount for x/y, or total values for z)
 * @property sizeBits  Element size in bits (8, 16, or 32)
 * @property signed    Whether the data is signed
 * @property lsbFirst  Byte order: true = little-endian, false = big-endian
 * @property unit      Display unit string
 * @property equation  Scaling equation (e.g. "0.75 * X", "40.0 * X")
 * @property decimalPl Decimal places for display
 * @property labels    For virtual axes: label values (index → string)
 * @property rowCount  For z-axis: number of rows
 * @property colCount  For z-axis: number of columns
 * @property min       Display minimum
 * @property max       Display maximum
 */
data class AxisSpec(
    val address: Int = -1,
    val count: Int = 1,
    val sizeBits: Int = 8,
    val signed: Boolean = false,
    val lsbFirst: Boolean = true,
    val unit: String = "",
    val equation: String = "X",
    val decimalPl: Int = 2,
    val labels: List<String> = emptyList(),
    val rowCount: Int = 1,
    val colCount: Int = 1,
    val min: Double = Double.NaN,
    val max: Double = Double.NaN
)
