package data.writer

import data.parser.xdf.TableDefinition
import domain.math.map.Map3d
import domain.model.optimizer.MapDelta
import domain.model.optimizer.SuggestedMaps
import java.io.File

/**
 * Phase 23: Export corrected maps as an XDF patch file.
 *
 * Generates an XDF file containing only the corrected map definitions with
 * updated Z-values. This can be loaded into TunerPro/WinOLS alongside the
 * original XDF to review changes before flashing.
 */
object XdfPatchWriter {

    /**
     * Write an XDF patch file containing all corrected maps.
     *
     * @param outputFile Target .xdf file
     * @param corrections Map of (TableDefinition, MapDelta) pairs to export
     * @param originalXdfTitle Title of the original XDF for reference
     */
    fun write(
        outputFile: File,
        corrections: List<Pair<TableDefinition, MapDelta>>,
        originalXdfTitle: String = "MxT Optimizer Corrections"
    ) {
        val sb = StringBuilder()
        sb.appendLine("""<?xml version="1.0" encoding="UTF-8"?>""")
        sb.appendLine("""<!-- Generated by MxT Optimizer -->""")
        sb.appendLine("""<!-- Original XDF: $originalXdfTitle -->""")
        sb.appendLine("""<!-- Maps corrected: ${corrections.size} -->""")
        sb.appendLine("""<XDFFORMAT version="1.60">""")
        sb.appendLine()
        sb.appendLine("""  <XDFHEADER>""")
        sb.appendLine("""    <flags>0x1</flags>""")
        sb.appendLine("""    <description>$originalXdfTitle — Optimizer Corrected Maps</description>""")
        sb.appendLine("""    <BASEOFFSET offset="0" subtract="0" />""")
        sb.appendLine("""    <DEFAULTS datasizeinbits="8" sigdigits="2" outputtype="1" signed="0" lsbfirst="0" float="0" />""")
        sb.appendLine("""    <REGION type="0xFFFFFFFF" startaddress="0x0" size="0x100000" regionflags="0x0" name="Binary File" desc="This region describes the bin file" />""")
        sb.appendLine("""  </XDFHEADER>""")
        sb.appendLine()

        for ((tableDef, delta) in corrections) {
            writeTable(sb, tableDef, delta)
        }

        sb.appendLine("""</XDFFORMAT>""")
        outputFile.writeText(sb.toString())
    }

    private fun writeTable(sb: StringBuilder, def: TableDefinition, delta: MapDelta) {
        val zAxis = def.zAxis
        sb.appendLine("""  <!-- ${def.tableName}: ${delta.cellsModified} cells modified, avg delta ${String.format("%.3f", delta.avgAbsoluteDelta)} -->""")
        sb.appendLine("""  <XDFTABLE uniqueid="0x0" flags="0x30">""")
        sb.appendLine("""    <title>${def.tableName} (Optimizer Corrected)</title>""")
        sb.appendLine("""    <description>${def.tableDescription} [Corrected by MxT Optimizer]</description>""")

        // X axis
        if (def.xAxis != null) {
            sb.appendLine("""    <XDFAXIS id="x" uniqueid="0x0">""")
            sb.appendLine("""      <EMBEDDEDDATA mmedaddress="0x${Integer.toHexString(def.xAxis.address)}" mmedelementsizebits="${def.xAxis.sizeBits}" mmedcolcount="${def.xAxis.indexCount}" mmedmajorstridebits="0" mmedminorstridebits="0" />""")
            sb.appendLine("""      <units>${def.xAxis.unit}</units>""")
            sb.appendLine("""      <indexcount>${def.xAxis.indexCount}</indexcount>""")
            sb.appendLine("""      <outputtype>1</outputtype>""")
            sb.appendLine("""      <MATH equation="${def.xAxis.equation}">""")
            sb.appendLine("""        <VAR id="${def.xAxis.varId}" />""")
            sb.appendLine("""      </MATH>""")
            sb.appendLine("""    </XDFAXIS>""")
        }

        // Y axis
        if (def.yAxis != null) {
            sb.appendLine("""    <XDFAXIS id="y" uniqueid="0x0">""")
            sb.appendLine("""      <EMBEDDEDDATA mmedaddress="0x${Integer.toHexString(def.yAxis.address)}" mmedelementsizebits="${def.yAxis.sizeBits}" mmedcolcount="${def.yAxis.indexCount}" mmedmajorstridebits="0" mmedminorstridebits="0" />""")
            sb.appendLine("""      <units>${def.yAxis.unit}</units>""")
            sb.appendLine("""      <indexcount>${def.yAxis.indexCount}</indexcount>""")
            sb.appendLine("""      <outputtype>1</outputtype>""")
            sb.appendLine("""      <MATH equation="${def.yAxis.equation}">""")
            sb.appendLine("""        <VAR id="${def.yAxis.varId}" />""")
            sb.appendLine("""      </MATH>""")
            sb.appendLine("""    </XDFAXIS>""")
        }

        // Z axis (data)
        sb.appendLine("""    <XDFAXIS id="z">""")
        sb.appendLine("""      <EMBEDDEDDATA mmedaddress="0x${Integer.toHexString(zAxis.address)}" mmedelementsizebits="${zAxis.sizeBits}" mmedrowcount="${zAxis.rowCount}" mmedcolcount="${zAxis.columnCount}" mmedmajorstridebits="0" mmedminorstridebits="0" />""")
        sb.appendLine("""      <units>${zAxis.unit}</units>""")
        sb.appendLine("""      <outputtype>1</outputtype>""")
        sb.appendLine("""      <MATH equation="${zAxis.equation}">""")
        sb.appendLine("""        <VAR id="${zAxis.varId}" />""")
        sb.appendLine("""      </MATH>""")
        sb.appendLine("""    </XDFAXIS>""")

        sb.appendLine("""  </XDFTABLE>""")
        sb.appendLine()
    }
}

